<a href="https://colab.research.google.com/github/Divyanshpanchal960/python/blob/main/practicesheetpandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df=pd.read_csv("/content/insurance - insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
print(df.head())
print(df.head(7))

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960

In [ ]:
print(df.tail())
print(df.tail(7))

      age     sex    bmi  children smoker     region     charges
1333   50    male  30.97         3     no  northwest  10600.5483
1334   18  female  31.92         0     no  northeast   2205.9808
1335   18  female  36.85         0     no  southeast   1629.8335
1336   21  female  25.80         0     no  southwest   2007.9450
1337   61  female  29.07         0    yes  northwest  29141.3603
      age     sex    bmi  children smoker     region      charges
1331   23  female  33.40         0     no  southwest  10795.93733
1332   52  female  44.70         3     no  southwest  11411.68500
1333   50    male  30.97         3     no  northwest  10600.54830
1334   18  female  31.92         0     no  northeast   2205.98080
1335   18  female  36.85         0     no  southeast   1629.83350
1336   21  female  25.80         0     no  southwest   2007.94500
1337   61  female  29.07         0    yes  northwest  29141.36030

In [ ]:
print(df.age)
print(df.abs)
print(df.bmi)

0       19
1       18
2       28
3       33
4       32
        ..
1333    50
1334    18
1335    18
1336    21
1337    61
Name: age, Length: 1338, dtype: int64
<bound method NDFrame.abs of       age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]>
0       27.900
1       33.770
2       33.000
3       22.705
4       28.880
         ...
1333    30.970
1334    31.920
1335    36.850
1336    25.800
1337    29.070
Name: bmi, Length: 1338, dtype: float64

In [ ]:
print(df.shape)
print(df.columns)
#check random index data----->
print(df.sample())
print(df.sample(4))

(1338, 7)
Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')
     age   sex    bmi  children smoker     region    charges
687   40  male  41.69         0     no  southeast  5438.7491
     age     sex     bmi  children smoker     region      charges
812   54    male  21.010         2     no  southeast  11013.71190
422   40    male  32.775         1    yes  northeast  39125.33225
851   61    male  32.300         2     no  northwest  14119.62000
978   45  female  39.995         3     no  northeast   9704.66805

In [ ]:
df['sex']

0       female
1         male
2         male
3         male
4         male
         ...
1333      male
1334    female
1335    female
1336    female
1337    female
Name: sex, Length: 1338, dtype: object

In [ ]:
df["sex"][0]='male'
df.head()
df["smoker"][0]='no'
df.head()

/tmp/ipython-input-1762754301.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["sex"][0]='male'
/tmp/ipython-input-1762754301.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["sex"][0]='male'
/tmp/ipython-input-1762754301.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["smoker"][0]='no'
/tmp/ipython-input-1762754301.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["smoker"][0]='no'

   age   sex     bmi  children smoker     region      charges
0   19  male  27.900         0     no  southwest  16884.92400
1   18  male  33.770         1     no  southeast   1725.55230
2   28  male  33.000         3     no  southeast   4449.46200
3   33  male  22.705         0     no  northwest  21984.47061
4   32  male  28.880         0     no  northwest   3866.85520

In [ ]:
df.describe()   #check statically view means dataframes numerical column

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [ ]:
#overall info check
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
df.loc[0:10,['smoker','age','sex']]

   smoker  age     sex
0     yes   19  female
1      no   18    male
2      no   28    male
3      no   33    male
4      no   32    male
5      no   31  female
6      no   46  female
7      no   37  female
8      no   37    male
9      no   60  female
10     no   25    male

In [ ]:
df.iloc[0:10,[0,1,2,3,4,5,6]]

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520
5   31  female  25.740         0     no  southeast   3756.62160
6   46  female  33.440         1     no  southeast   8240.58960
7   37  female  27.740         3     no  northwest   7281.50560
8   37    male  29.830         2     no  northeast   6406.41070
9   60  female  25.840         0     no  northwest  28923.13692

In [ ]:
print(df['sex'].value_counts())
print(df['smoker'].value_counts())
print(df['smoker'].value_counts('male'))
print(df['smoker'].value_counts('female'))

sex
male      677
female    661
Name: count, dtype: int64
smoker
no     1065
yes     273
Name: count, dtype: int64
smoker
no     0.795964
yes    0.204036
Name: proportion, dtype: float64
smoker
no     0.795964
yes    0.204036
Name: proportion, dtype: float64

In [ ]:
print(df['region'].value_counts())
print(df['sex'].value_counts())

region
southeast    364
southwest    325
northwest    325
northeast    324
Name: count, dtype: int64
sex
male      677
female    661
Name: count, dtype: int64

In [ ]:
print(df.groupby('sex')['smoker'].size())
# print(df.groupby('children')['smoker'].size())
# print(df.columns)

sex
female    661
male      676
trans       1
Name: smoker, dtype: int64

In [ ]:
df.isnull().sum()
#print(df.isnull().avg)

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
#fill_missing values or drop the row
print(df['charges'])
print(df['charges'].mean())
print(df['smoker'].mean())

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64
13270.422265141257

TypeError: Could not convert string 'nononononononononononoyesnonoyesnonononoyesnononoyesnononononoyesyesnononoyesnononoyesyesnononononononononoyesnonoyesyesnoyesnoyesyesnononononoyesnonononoyesyesnononononononononononoyesnoyesyesyesnononononoyesnoyesnononoyesyesnononoyesnoyesnononoyesnononononononoyesnononononoyesnonoyesnoyesnononononononononononononoyesnoyesnoyesnonononononoyesnonoyesyesyesnoyesyesnononononononononononononoyesnononononononononoyesnononononononononononononononononoyesnononoyesnononononononononononononononoyesyesnonononononononononoyesnonoyesnoyesnononoyesnononononoyesyesyesnoyesnoyesnonoyesnoyesyesyesnoyesyesnonononoyesnonononononononoyesyesnonononononoyesnononoyesnononoyesyesyesnonoyesnonononononononononoyesnoyesnononononononoyesnonononoyesyesnoyesyesnonononononoyesnononononononononononononononononononononononoyesnonononononononononoyesnoyesyesyesnonoyesyesnononononononononononononononononononononononononononononoyesyesnonononoyesnoyesyesyesyesnonononononononononononononononononoyesnonoyesnonononononononononononononononoyesnononoyesnonononononononoyesyesyesnononononononononononoyesnononononoyesnononononoyesnoyesyesnonononononononononoyesnononononononononoyesnononononoyesnonononononononononononoyesnoyesnononoyesnonononononononoyesnonononononononononoyesnononononononoyesnononononononononoyesnononononoyesnonononononononononoyesnonoyesnoyesnononononoyesnoyesyesnonoyesnoyesnononononoyesnonononononononoyesnonoyesnononononononononononononoyesnonononononononoyesyesnoyesyesnononononoyesnonoyesnonononoyesnonononononoyesnononononononoyesnonononononononoyesnonononononononononononononononononoyesnoyesnonoyesnononononoyesnoyesyesnoyesyesnononononononoyesnonononononoyesnoyesnonoyesnonononononononononoyesnonononononoyesnonoyesnononononononononoyesnoyesnononoyesnononoyesnonononononononononononononoyesyesnonononononoyesyesyesnononononononononononononoyesyesnoyesnonononoyesnoyesnoyesnoyesyesnonoyesnonononononononononononononononononononononoyesnoyesyesnononoyesnonoyesnonoyesnonononoyesnononononononoyesnoyesnonononoyesyesnononononononononononononononononononononononononononononoyesnoyesnoyesnoyesyesnoyesnoyesnononononononoyesnonononononononoyesnonononononoyesnonononononoyesnonononoyesnononononoyesyesnononononoyesnononoyesnononononononononoyesyesnononoyesnononoyesyesnoyesnonoyesyesnonoyesnoyesnonoyesnoyesnoyesnononoyesnonononononononoyesnononononononoyesnononononononoyesnonononononoyesnonononoyesnonoyesnonoyesnononoyesnonononononononononoyesyesnonononoyesyesnoyesnoyesnoyesnonononononononononononononoyesnonononononoyesnononononoyesnononoyesnononononononononononononoyesyesnonononoyesnonoyesnonononoyesnoyesnoyesnononononononoyesnononononononoyesnonoyesyesnononononononononoyesnonononoyesnonononononoyesyesnonononononononoyesyesnononononononoyesyesnoyesnonononononononononononoyesnoyesnonononononoyesnononoyesnonoyesyesnoyesnononoyesnonoyesnonononononononoyesyesnoyesyesnoyesyesyesnonononoyesyesnonononononoyesnoyesnononononononononononononoyes' to numeric

In [ ]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [ ]:
print(df['smoker'].mode())
print(df['smoker'].value_counts())
print(df['sex'].value_counts())

0    no
Name: smoker, dtype: object
smoker
no     1065
yes     273
Name: count, dtype: int64
sex
male      677
female    661
Name: count, dtype: int64

In [ ]:
df.to_csv("insurance.csv")
df

      age     sex     bmi  children smoker     region      charges
0      19    male  27.900         0     no  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [ ]:
#df.describe()
#df.head(21)
df['sex'][3][4]='trans'
df
#df['region'].value_counts()

TypeError: 'str' object does not support item assignment